Fixed race condition in CacheImpl.Close() (#287)
There is a race condition that is popping up in tests:

```
==================
WARNING: DATA RACE
Write at 0x00c00051b9f0 by goroutine 456:
  runtime.closechan()
      /opt/hostedtoolcache/go/1.19.6/x64/src/runtime/chan.go:357 +0x0
  github.com/dgraph-io/ristretto.(*Cache).Close()
      /home/runner/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.1/cache.go:361 +0xc4
  oxia/oxia.(*cacheImpl[...]).Close()
      /home/runner/work/oxia/oxia/oxia/cache.go:321 +0x56
  oxia/oxia.(*cacheImpl[...]).Close()
      <autogenerated>:1 +0x3c
  oxia/oxia.TestCache_InsertionDeletion()
      /home/runner/work/oxia/oxia/oxia/cache_test.go:130 +0xe89
  testing.tRunner()
      /opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1493 +0x47

Previous read at 0x00c00051b9f0 by goroutine 479:
  runtime.chansend()
      /opt/hostedtoolcache/go/1.19.6/x64/src/runtime/chan.go:160 +0x0
  github.com/dgraph-io/ristretto.(*Cache).Del()
      /home/runner/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.1/cache.go:317 +0x1d7
  oxia/oxia.(*cacheImpl[...]).handleNotification()
      /home/runner/work/oxia/oxia/oxia/cache.go:225 +0x96
  oxia/oxia.(*cacheImpl[...]).handleNotification()
      <autogenerated>:1 +0x46
  oxia/oxia.(*cacheManager).handleNotification()
      /home/runner/work/oxia/oxia/oxia/cache.go:161 +0x281
  oxia/oxia.(*cacheManager).run()
      /home/runner/work/oxia/oxia/oxia/cache.go:141 +0x70
  oxia/oxia.(*cacheManager).run-fm()
      <autogenerated>:1 +0x39
  oxia/common.DoWithLabels.func1()
      /home/runner/work/oxia/oxia/common/pprof.go:43 +0x30
  runtime/pprof.Do()
      /opt/hostedtoolcache/go/1.19.6/x64/src/runtime/pprof/runtime.go:40 +0x122
  oxia/common.DoWithLabels()
      /home/runner/work/oxia/oxia/common/pprof.go:39 +0x4f0
  oxia/oxia.newCacheManager.func1()
      /home/runner/work/oxia/oxia/oxia/cache.go:127 +0x47

Goroutine 456 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1493 +0x75d
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1846 +0x99
  testing.tRunner()
      /opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1446 +0x216
  testing.runTests()
      /opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1844 +0x7ec
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1726 +0xa84
  oxia/oxia.TestMain()
      /home/runner/work/oxia/oxia/oxia/cache_test.go:43 +0x291
  main.main()
      _testmain.go:149 +0x404

Goroutine 479 (running) created at:
  oxia/oxia.newCacheManager()
      /home/runner/work/oxia/oxia/oxia/cache.go:127 +0x3da
  oxia/oxia.(*syncClientImpl).getCacheManager()
      /home/runner/work/oxia/oxia/oxia/sync_client_impl.go:65 +0x10a
  oxia/oxia.NewCache[...]()
      /home/runner/work/oxia/oxia/oxia/cache.go:90 +0xa6
  oxia/oxia.TestCache_InsertionDeletion()
      /home/runner/work/oxia/oxia/oxia/cache_test.go:83 +0xb4
  testing.tRunner()
      /opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1493 +0x47
==================
--- FAIL: TestCache_InsertionDeletion (0.09s)
    testing.go:1319: race detected during execution of test
```

The reason is that we're still getting notifications while we're closing
the cache.

### Modifications 

 1. Close the notifications before closing the ristretto cache
2. Ensuring that `Notifications.Close()` waits until all the goroutines
are stopped and the channel is emptied