Fixed race condition in Follower.replicate() (#234)
There is a race condition in `FollowerController.Replicate()` and
`SendSnapshot()`.

The symptom is an intermittent test failure: 

```
Jan 20 00:21:22.963982 INF Created follower commit-offset=-1 component=follower-controller head-offset=0 shard=0 term=5
Jan 20 00:21:22.964387 WRN Error in handle Replicate stream error="rpc error: code = Code(101) desc = oxia: invalid term" component=follower-controller shard=0 term=5
Jan 20 00:21:22.964604 DBG Closing follower controller component=follower-controller shard=0 term=5
--- FAIL: TestFollowerController_RejectEntriesWithDifferentTerm (0.03s)
    follower_controller_test.go:451: 
        	Error Trace:	/home/runner/work/oxia/oxia/server/follower_controller_test.go:451
        	Error:      	Not equal: 
        	            	expected: 0x65
        	            	actual  : 0x0
        	Test:       	TestFollowerController_RejectEntriesWithDifferentTerm
```

The failure can be reproduced by putting a sleep in this line:
https://github.com/streamnative/oxia/blob/039312c0ec127165e378caeb3bfcd1d6753879e7/server/follower_controller.go#L320

The reason is that the test is expecting a failure (for invalid term),
and the background go-routine that processes the append requests finds
immediately an entry to process, with invalid entry.

Therefore it tries to close the stream channel with the appropriate
error, but when the race condition occours, the main go-routine still
hasn't started listening on the error channel.

The other go-routine doesn't write if there's no one listening and the
error is lost.

To solve this, change the channel into a WaitGroup that will make sure
the error is not lost.

Co-authored-by: Dave Maughan <dave.maughan@streamnative.io>